# build and serve multi-container application
# use this: docker-compose -f docker-compose.yml up --build -d

services:
  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: socialapp-frontend
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - socialapp-network
    restart: unless-stopped

  # Java Spring Boot Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: socialapp-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - socialapp-network
    volumes:
      - backend-data:/app/data
    restart: unless-stopped

networks:
  socialapp-network:
    driver: bridge
    name: socialapp-network

volumes:
  backend-data:
    name: socialapp-backend-data
  portainer-data:
    name: portainer-data